sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cxl5288311
  alioss:
    access-key-id: LTAI5tCXaZvAvXh5vMzPhERe
    access-key-secret: npl39kbhJIi8qcCEr8bVmgEUcgRQWX
    bucket-name: cxl-sky
    endpoint: oss-cn-chengdu.aliyuncs.com
