sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cxl5288311
  alioss:
    access-key-id: LTAI5tCXaZvAvXh5vMzPhERe
    access-key-secret: npl39kbhJIi8qcCEr8bVmgEUcgRQWX
    bucket-name: cxl-sky
    endpoint: oss-cn-chengdu.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wx2d3d94a545600cf7
    secret: c0a27cdb1288f0647c49f739e21d61f4
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess

